### ISSUE TITLE
JavaScript minification

### ISSUE THREAD

**Issue by damianfrizzi** [damianfrizzi/fetoolkit#13]
## Feature
Add minification to the JS/TS formatter.

**Comment by RodrigoTomeES** [comment]
Can you also add minification for HTML, CSS and other types of file?

**Comment by damianfrizzi** [comment]
@RodrigoTomeES CSS minification is already on the site ("Format CSS" widget). I will consider adding HTML minification 👍

**Comment by RodrigoTomeES** [comment]
Oh it's true, I hadn't seen it. Thanks for his work!

**Comment by damianfrizzi** [comment]
JS minification is now included in the "Format JS/TS" widget.
