### ISSUE TITLE
UUID Generator

### ISSUE THREAD

**Issue by denizguzel** [damianfrizzi/fetoolkit#22]
## Feature
Maybe UUID generator would be cool to have too.

Example: [https://www.uuidgenerator.net/](url)

Example NPM Package: [https://www.npmjs.com/package/uuid](url)

**Comment by damianfrizzi** [comment]
Hey @denizguzel, I added functionality to define custom widgets with which you could add a uuid generator widget on your own. I used https://www.guidgenerator.com/ for my tests. I'll monitor usage and keep this issue open in case many people are using it (and will provide an out of the box solution).
