### ISSUE TITLE
Enhance widget descriptions

### ISSUE THREAD

**Issue by pablo-miralles** [damianfrizzi/fetoolkit#27]
## Feature

This is a request for new users like me.

Now, If we want to see what X widget does, we have to open it or use it (for example, if I want to know what the SVG converter widget does, I have to upload an SVG). It will be awesome to have a small description of the widget in each one, to know how all of them work in an easy way.

I thought 2 ways to do it:
- The first one, just a info page in the application, where you have listed all the widget an their descriptions (all in one page)
- The second way is to add to all widgets a small description, like the ones are not activated in the bottom. And maybe, a toggle to hide all descriptions if they are annoying.

**Comment by damianfrizzi** [comment]
Awesome feedback, thanks! 
I'm currently working on another feature but this will become the next item on my list.

What do you think about adding a tooltip with the description of the widget to its title (maybe indicated with a small "info" icon)? I'd prefer to keep the widget preview as minimal as possible.

**Comment by pablo-miralles** [comment]
It would be perfect, because this tool us meant to be used on a desktop.

Thank you for considering!

**Comment by damianfrizzi** [comment]
Hey @pablo-miralles, I just released a new version including a description tooltip for each widget title. I hope you like it!
I'm going to close this issue. If you have more feedback I'd appreciate if you open another issue :)
